### ISSUE TITLE
Game crash: Miner's Delight encountered an error during the common_setup phase

### ISSUE THREAD

**Issue by CTsquared** [SammySemicolon/MinersDelight#8]
Game crashes upon startup, throwing this error:
Miner's Delight encountered an error during the common_setup phase
java.lang.RuntimeException: Unexpected error while registering entry miners_delight:stuffed_squid to registry minecraft:item

Crash log:
[crash-2022-11-23_16.01.20-fml.txt](https://github.com/SammySemicolon/MinersDelight/files/10079852/crash-2022-11-23_16.01.20-fml.txt)

**Comment by SammySemicolon** [comment]
I've no idea what this error is. Try getting rid of optifine

**Comment by LimonBlaze** [comment]
> I've no idea what this error is. Try getting rid of optifine

I believe it's because @CTsquared is using Farmer's Delight 1.1.2 instead of 1.2.+.
The `SERVINGS` property had been hardcoded in `FeastBlock` before Rice Roll Medley was added in 1.2.0.
See: https://github.com/vectorwing/FarmersDelight/commit/552ba5b81d3a630cbd2fa0f9cbae88785aabac83#diff-0898b5a0c8c3465bdf8ee0a8d6d6f114b71f422d79135b45ee0206b874d75014

Miner's Delight should have declared Farmer's Delight 1.2.+ as a dependency in [`mods.toml`](https://github.com/SammySemicolon/MinersDelight/blob/main/src/main/resources/META-INF/mods.toml)
